name: rachelfontaine
favicon: null
layout_spectrum: 0.2578128280583769
typography_spectrum: 0.5910983020439744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5132474673446268
  lightness: 0.9632735098712146
  saturation: 0.9370684500318021
  rhythmicContrast: 0.4116458685602993
purpose: []
